# Generated by Django 5.0.6 on 2024-07-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
